/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificateIndexRouteImport } from './routes/certificate.index'
import { Route as CertificateSealRouteImport } from './routes/certificate.$seal'

const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateIndexRoute = CertificateIndexRouteImport.update({
  id: '/certificate/',
  path: '/certificate/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateSealRoute = CertificateSealRouteImport.update({
  id: '/certificate/$seal',
  path: '/certificate/$seal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/license': typeof LicenseRoute
  '/pulse': typeof PulseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/toolkit': typeof ToolkitRoute
  '/volumes': typeof VolumesRoute
  '/certificate/$seal': typeof CertificateSealRoute
  '/certificate/': typeof CertificateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/license': typeof LicenseRoute
  '/pulse': typeof PulseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/toolkit': typeof ToolkitRoute
  '/volumes': typeof VolumesRoute
  '/certificate/$seal': typeof CertificateSealRoute
  '/certificate': typeof CertificateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/license': typeof LicenseRoute
  '/pulse': typeof PulseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/toolkit': typeof ToolkitRoute
  '/volumes': typeof VolumesRoute
  '/certificate/$seal': typeof CertificateSealRoute
  '/certificate/': typeof CertificateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/letter'
    | '/license'
    | '/pulse'
    | '/sitemap.xml'
    | '/toolkit'
    | '/volumes'
    | '/certificate/$seal'
    | '/certificate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/letter'
    | '/license'
    | '/pulse'
    | '/sitemap.xml'
    | '/toolkit'
    | '/volumes'
    | '/certificate/$seal'
    | '/certificate'
  id:
    | '__root__'
    | '/'
    | '/letter'
    | '/license'
    | '/pulse'
    | '/sitemap.xml'
    | '/toolkit'
    | '/volumes'
    | '/certificate/$seal'
    | '/certificate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LetterRoute: typeof LetterRoute
  LicenseRoute: typeof LicenseRoute
  PulseRoute: typeof PulseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolkitRoute: typeof ToolkitRoute
  VolumesRoute: typeof VolumesRoute
  CertificateSealRoute: typeof CertificateSealRoute
  CertificateIndexRoute: typeof CertificateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/': {
      id: '/certificate/'
      path: '/certificate'
      fullPath: '/certificate/'
      preLoaderRoute: typeof CertificateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$seal': {
      id: '/certificate/$seal'
      path: '/certificate/$seal'
      fullPath: '/certificate/$seal'
      preLoaderRoute: typeof CertificateSealRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LetterRoute: LetterRoute,
  LicenseRoute: LicenseRoute,
  PulseRoute: PulseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolkitRoute: ToolkitRoute,
  VolumesRoute: VolumesRoute,
  CertificateSealRoute: CertificateSealRoute,
  CertificateIndexRoute: CertificateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
